name: github release

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    permissions:
      contents: write  # for ncipollo/release-action to create a release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v2.6.0

    - name: Setup jdk
      uses: actions/setup-java@9704b39bf258b59bc04b50fa2dd55e9ed76b47a8 # main
      with:
        java-version: 21
        distribution: 'adopt'

    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install ruby-asciidoctor-pdf antlr4 pcregrep asciidoc-base

    - name: build release
      run: make release

    - name: Read VERSION file
      id: getversion
      run: echo "::set-output name=version::$(cat version.txt)"

    - uses: ncipollo/release-action@2c591bcc8ecdcd2db72b97d6147f871fcd833ba5 # v1.14.0
      with:
        artifacts: "fuzion_${{ steps.getversion.outputs.version }}.tar.gz"
        tag: "v${{ steps.getversion.outputs.version }}"
        prerelease: false
        generateReleaseNotes: false
        token: ${{ secrets.GITHUB_TOKEN }}
