name: github release

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    permissions:
      contents: write  # for ncipollo/release-action to create a release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v2.6.0

    - name: Setup jdk-17
      uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 # main
      with:
        java-version: 17
        distribution: 'adopt'

  # NYI ebnf is not generated because of missing antlr/pcregrep
    - name: build release
      run: make release

    - name: Read VERSION file
      id: getversion
      run: echo "::set-output name=version::$(cat version.txt)"

    - uses: ncipollo/release-action@6c75be85e571768fa31b40abf38de58ba0397db5 # v1.13.0
      with:
        artifacts: "fuzion_${{ steps.getversion.outputs.version }}.tar.gz"
        tag: "v${{ steps.getversion.outputs.version }}"
        prerelease: false
        generateReleaseNotes: false
        token: ${{ secrets.GITHUB_TOKEN }}
